# Generated by Django 2.2.7 on 2019-11-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_arbitro', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50)),
                ('imagen', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArregloEncuentro',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuentro', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('fecha_fundacion', models.DateField()),
                ('esquema_habitual', models.CharField(blank=True, max_length=20)),
                ('logo_equipo', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('dorsal', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estadio', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionArbitro',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionJugador',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAmonestaciones',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_amonestacion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartidoJugado',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('arbitros', models.ManyToManyField(to='API_torneo.Arbitro')),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.ArregloEncuentro')),
                ('equipo_jugador', models.ManyToManyField(to='API_torneo.EquipoJugador')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Estadio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.URLField(blank=True)),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.PosicionJugador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.EquipoJugador')),
                ('partido_jugado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.PartidoJugado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipojugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Estadio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(through='API_torneo.EquipoJugador', to='API_torneo.Jugador'),
        ),
        migrations.AddField(
            model_name='arregloencuentro',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_local', to='API_torneo.Equipo'),
        ),
        migrations.AddField(
            model_name='arregloencuentro',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_visitante', to='API_torneo.Equipo'),
        ),
        migrations.AddField(
            model_name='arregloencuentro',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Temporada'),
        ),
        migrations.CreateModel(
            name='Amonestaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('amonestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.TipoAmonestaciones')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.EquipoJugador')),
                ('partido_jugado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.PartidoJugado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
