# Generated by Django 2.2.7 on 2019-11-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='Arbitros')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuentro', models.DateField()),
                ('fecha_partido_jugado', models.DateTimeField(null=True)),
                ('arbitros', models.ManyToManyField(null=True, to='API_torneo.Arbitro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_fundacion', models.DateField()),
                ('esquema_habitual', models.CharField(blank=True, max_length=20)),
                ('logo_equipo', models.ImageField(blank=True, upload_to='Logos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('dorsal', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionArbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAmonestaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('identidad', models.CharField(max_length=13, unique=True)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, upload_to='Jugadores')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.PosicionJugador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.EquipoJugador')),
                ('partido_jugado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Encuentro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipojugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Estadio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(through='API_torneo.EquipoJugador', to='API_torneo.Jugador'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_jugador',
            field=models.ManyToManyField(null=True, to='API_torneo.EquipoJugador'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_local', to='API_torneo.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_visitante', to='API_torneo.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='estadio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Estadio'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Temporada'),
        ),
        migrations.CreateModel(
            name='Amonestaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('amonestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.TipoAmonestaciones')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.EquipoJugador')),
                ('partido_jugado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Encuentro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
