# Generated by Django 2.2.7 on 2019-11-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_torneo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='arbitros',
            field=models.ManyToManyField(to='API_torneo.Arbitro'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='equipo_jugador',
            field=models.ManyToManyField(to='API_torneo.EquipoJugador'),
        ),
    ]
