# Generated by Django 2.2.7 on 2019-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_torneo', '0002_auto_20191123_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosicionArbitro',
        ),
        migrations.AddField(
            model_name='arbitro',
            name='posicion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Arbitro Principal'), (2, 'Arbitro Asistente 1'), (3, 'Arbitro Asistente 2'), (4, 'Cuarto Arbitro'), (5, 'Quinto Arbitro'), (6, 'Sexto Arbitro')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amonestaciones',
            name='amonestacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Amarilla'), (2, 'roja')]),
        ),
    ]
