# Generated by Django 2.2.7 on 2019-12-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_torneo', '0004_auto_20191202_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='goles',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goles',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_torneo.Jugador'),
        ),
    ]
